"""create users table (Sprint P3: authentication + RBAC)

Revision ID: 1f20f57819a3
Revises: 06b17a0f30ad
Create Date: 2026-07-14 00:00:00.000000

Hand-written (not autogenerated) for the same reason as 06b17a0f30ad: no
PostgreSQL instance or network access available in the sandbox this was
written in. Written directly from app/models/user.py; verify against a
real database before merging (see docs/P1_LOCAL_VERIFICATION.md).
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "1f20f57819a3"
down_revision: Union[str, None] = "06b17a0f30ad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "viewer", "operator", "admin",
                name="user_role",
                native_enum=False,
                length=16,
            ),
            nullable=False,
            server_default="viewer",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "active", "disabled",
                name="user_status",
                native_enum=False,
                length=16,
            ),
            nullable=False,
            server_default="pending",
        ),
        sa.Column(
            "is_verified", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="pk_users"),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    op.create_index("ix_users_role", "users", ["role"], unique=False)
    op.create_index("ix_users_status", "users", ["status"], unique=False)


def downgrade() -> None:
    op.drop_index("ix_users_status", table_name="users")
    op.drop_index("ix_users_role", table_name="users")
    op.drop_index("ix_users_email", table_name="users")
    op.drop_table("users")
